### ISSUE TITLE
Will the paper be released on ArXiv?

### ISSUE THREAD

**Issue by MengzhangLI** [lygsbw/segdeformer#2]
Hi, will this paper be available on ArXiv?

The question is for many people like me, we can find it has been accepted in ECCV'2022 and can be found in [springer link](https://link.springer.com/chapter/10.1007/978-3-031-19815-1_36), but most of us do not have accounts to view the full paper.

Best,

**Comment by MengzhangLI** [comment]
For example, currently we can not see the detailed numerical results in public, neither nor ckpts which are usually released on Github repo.

Thanks in advance!

**Comment by lygsbw** [comment]
Thanks for your attention,

We have added a [link]((https://www.ecva.net/papers/eccv_2022/papers_ECCV/html/383_ECCV_2022_paper.php) to our paper in the updated README file. Numerical results on ADE20K and their corresponding training logs are also included. 

As to ckpts, due to the complex inner review process, it is difficult for them to be released in a short time. We will continue to facilitate this process.
